export const VITE_API_URL="https://distribute-dealers-trial-scholarships.trycloudflare.com"
export const VITE_AVATAR_URL="https://distribute-dealers-trial-scholarships.trycloudflare.com/storage/avatar"
export const VITE_BACKGROUND_URL="https://distribute-dealers-trial-scholarships.trycloudflare.com/storage/background"
export const VITE_COURSE_IMAGE_URL="https://distribute-dealers-trial-scholarships.trycloudflare.com/storage/course"
export const VITE_LECTURE_URL="https://distribute-dealers-trial-scholarships.trycloudflare.com/storage/lecture"
